version: '3.9'

services:
  mysqldb:
    image: mysql:8.3.0
    container_name: mysql-taskmanagement
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: naotemsenha
      MYSQL_DATABASE: task-management

volumes:
  db:

